<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('orders')->insert([
            // ========== АПРЕЛЬ 2026 (завершённые заказы) ==========
            [
                'type' => 'order',
                'client_id' => 1,
                'client_name' => null,
                'client_phone' => '+7 (999) 111-11-11',
                'delivery_date' => '2026-04-03',
                'delivery_time' => '14:00:00',
                'assembly_date' => '2026-04-02',
                'status' => 'completed',
                'total_amount' => 2250.00,
                'payment_method' => 'card',
                'comment' => 'Поздравительная открытка',
                'user_id' => 2,
                'created_at' => '2026-04-01 10:00:00',
                'updated_at' => '2026-04-03 14:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => null,
                'client_name' => 'Смирнова Елена',
                'client_phone' => '+7 (999) 222-22-22',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 960.00,
                'payment_method' => 'cash',
                'comment' => 'Букет на день рождения',
                'user_id' => 2,
                'created_at' => '2026-04-05 15:30:00',
                'updated_at' => '2026-04-05 15:30:00'
            ],
            [
                'type' => 'order',
                'client_id' => 2,
                'client_name' => null,
                'client_phone' => '+7 (999) 333-33-33',
                'delivery_date' => '2026-04-10',
                'delivery_time' => '12:00:00',
                'assembly_date' => '2026-04-09',
                'status' => 'completed',
                'total_amount' => 1850.00,
                'payment_method' => 'card',
                'comment' => 'Свадебный букет',
                'user_id' => 3,
                'created_at' => '2026-04-08 09:00:00',
                'updated_at' => '2026-04-10 12:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 3,
                'client_name' => null,
                'client_phone' => '+7 (999) 444-44-44',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 1300.00,
                'payment_method' => 'card',
                'comment' => 'Корпоративный заказ',
                'user_id' => 3,
                'created_at' => '2026-04-12 14:00:00',
                'updated_at' => '2026-04-12 14:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 4,
                'client_name' => null,
                'client_phone' => '+7 (999) 555-55-55',
                'delivery_date' => '2026-04-15',
                'delivery_time' => '16:00:00',
                'assembly_date' => '2026-04-14',
                'status' => 'completed',
                'total_amount' => 2800.00,
                'payment_method' => 'card',
                'comment' => 'Юбилей',
                'user_id' => 2,
                'created_at' => '2026-04-13 11:00:00',
                'updated_at' => '2026-04-15 16:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 5,
                'client_name' => null,
                'client_phone' => '+7 (999) 666-66-66',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 540.00,
                'payment_method' => 'cash',
                'comment' => null,
                'user_id' => 2,
                'created_at' => '2026-04-18 18:00:00',
                'updated_at' => '2026-04-18 18:00:00'
            ],

            // ========== МАЙ 2026 (разные статусы) ==========
            [
                'type' => 'order',
                'client_id' => 6,
                'client_name' => null,
                'client_phone' => '+7 (999) 777-77-77',
                'delivery_date' => '2026-05-03',
                'delivery_time' => '14:00:00',
                'assembly_date' => '2026-05-02',
                'status' => 'completed',
                'total_amount' => 2250.00,
                'payment_method' => 'card',
                'comment' => 'Поздравительная открытка',
                'user_id' => 2,
                'created_at' => '2026-05-01 10:00:00',
                'updated_at' => '2026-05-03 14:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => null,
                'client_name' => 'Петрова Анна',
                'client_phone' => '+7 (999) 888-88-88',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 960.00,
                'payment_method' => 'cash',
                'comment' => 'Букет на день рождения',
                'user_id' => 2,
                'created_at' => '2026-05-05 15:30:00',
                'updated_at' => '2026-05-05 15:30:00'
            ],
            [
                'type' => 'order',
                'client_id' => 7,
                'client_name' => null,
                'client_phone' => '+7 (999) 999-99-99',
                'delivery_date' => '2026-05-07',
                'delivery_time' => '12:00:00',
                'assembly_date' => '2026-05-06',
                'status' => 'assembly',
                'total_amount' => 1850.00,
                'payment_method' => 'card',
                'comment' => 'Свадебный букет',
                'user_id' => 3,
                'created_at' => '2026-05-04 09:00:00',
                'updated_at' => '2026-05-07 12:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 8,
                'client_name' => null,
                'client_phone' => '+7 (999) 101-01-01',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 1300.00,
                'payment_method' => 'card',
                'comment' => 'Корпоративный заказ',
                'user_id' => 3,
                'created_at' => '2026-05-06 14:00:00',
                'updated_at' => '2026-05-06 14:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 9,
                'client_name' => null,
                'client_phone' => '+7 (999) 202-02-02',
                'delivery_date' => '2026-05-10',
                'delivery_time' => '16:00:00',
                'assembly_date' => '2026-05-09',
                'status' => 'ready',
                'total_amount' => 2800.00,
                'payment_method' => 'card',
                'comment' => 'Юбилей',
                'user_id' => 2,
                'created_at' => '2026-05-08 11:00:00',
                'updated_at' => '2026-05-10 16:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 10,
                'client_name' => null,
                'client_phone' => '+7 (999) 303-03-03',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 540.00,
                'payment_method' => 'cash',
                'comment' => null,
                'user_id' => 2,
                'created_at' => '2026-05-10 18:00:00',
                'updated_at' => '2026-05-10 18:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 11,
                'client_name' => null,
                'client_phone' => '+7 (999) 404-04-04',
                'delivery_date' => '2026-05-12',
                'delivery_time' => '13:00:00',
                'assembly_date' => '2026-05-11',
                'status' => 'new',
                'total_amount' => 3200.00,
                'payment_method' => 'card',
                'comment' => 'День рождения',
                'user_id' => 3,
                'created_at' => '2026-05-09 09:00:00',
                'updated_at' => '2026-05-12 13:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 12,
                'client_name' => null,
                'client_phone' => '+7 (999) 505-05-05',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 720.00,
                'payment_method' => 'card',
                'comment' => null,
                'user_id' => 2,
                'created_at' => '2026-05-12 16:00:00',
                'updated_at' => '2026-05-12 16:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 13,
                'client_name' => null,
                'client_phone' => '+7 (999) 606-06-06',
                'delivery_date' => '2026-05-15',
                'delivery_time' => '15:00:00',
                'assembly_date' => '2026-05-14',
                'status' => 'cancelled',
                'total_amount' => 1950.00,
                'payment_method' => null,
                'comment' => 'Клиент отменил',
                'user_id' => 2,
                'created_at' => '2026-05-13 10:00:00',
                'updated_at' => '2026-05-15 15:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 14,
                'client_name' => null,
                'client_phone' => '+7 (999) 707-07-07',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 450.00,
                'payment_method' => 'cash',
                'comment' => null,
                'user_id' => 3,
                'created_at' => '2026-05-14 11:00:00',
                'updated_at' => '2026-05-14 11:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 15,
                'client_name' => null,
                'client_phone' => '+7 (999) 808-08-08',
                'delivery_date' => '2026-05-18',
                'delivery_time' => '11:00:00',
                'assembly_date' => '2026-05-17',
                'status' => 'completed',
                'total_amount' => 2400.00,
                'payment_method' => 'card',
                'comment' => 'Поздравление',
                'user_id' => 2,
                'created_at' => '2026-05-15 09:00:00',
                'updated_at' => '2026-05-18 11:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 16,
                'client_name' => null,
                'client_phone' => '+7 (999) 909-09-09',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 890.00,
                'payment_method' => 'card',
                'comment' => null,
                'user_id' => 3,
                'created_at' => '2026-05-16 14:00:00',
                'updated_at' => '2026-05-16 14:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 17,
                'client_name' => null,
                'client_phone' => '+7 (999) 010-01-01',
                'delivery_date' => '2026-05-20',
                'delivery_time' => '14:00:00',
                'assembly_date' => '2026-05-19',
                'status' => 'new',
                'total_amount' => 1750.00,
                'payment_method' => 'card',
                'comment' => 'Юбилей',
                'user_id' => 2,
                'created_at' => '2026-05-17 12:00:00',
                'updated_at' => '2026-05-20 14:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 18,
                'client_name' => null,
                'client_phone' => '+7 (999) 121-12-12',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 630.00,
                'payment_method' => 'cash',
                'comment' => null,
                'user_id' => 2,
                'created_at' => '2026-05-18 15:00:00',
                'updated_at' => '2026-05-18 15:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 19,
                'client_name' => null,
                'client_phone' => '+7 (999) 131-13-13',
                'delivery_date' => '2026-05-22',
                'delivery_time' => '12:00:00',
                'assembly_date' => '2026-05-21',
                'status' => 'assembly',
                'total_amount' => 3100.00,
                'payment_method' => 'card',
                'comment' => 'Свадьба',
                'user_id' => 3,
                'created_at' => '2026-05-19 10:00:00',
                'updated_at' => '2026-05-22 12:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 20,
                'client_name' => null,
                'client_phone' => '+7 (999) 141-14-14',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 520.00,
                'payment_method' => 'card',
                'comment' => null,
                'user_id' => 2,
                'created_at' => '2026-05-20 17:00:00',
                'updated_at' => '2026-05-20 17:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 1,
                'client_name' => null,
                'client_phone' => '+7 (999) 151-15-15',
                'delivery_date' => '2026-05-25',
                'delivery_time' => '16:00:00',
                'assembly_date' => '2026-05-24',
                'status' => 'ready',
                'total_amount' => 2650.00,
                'payment_method' => 'card',
                'comment' => 'День рождения',
                'user_id' => 2,
                'created_at' => '2026-05-21 09:00:00',
                'updated_at' => '2026-05-25 16:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 2,
                'client_name' => null,
                'client_phone' => '+7 (999) 161-16-16',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 380.00,
                'payment_method' => 'cash',
                'comment' => null,
                'user_id' => 3,
                'created_at' => '2026-05-22 19:00:00',
                'updated_at' => '2026-05-22 19:00:00'
            ],
            [
                'type' => 'order',
                'client_id' => 3,
                'client_name' => null,
                'client_phone' => '+7 (999) 171-17-17',
                'delivery_date' => '2026-05-28',
                'delivery_time' => '15:00:00',
                'assembly_date' => '2026-05-27',
                'status' => 'cancelled',
                'total_amount' => 2200.00,
                'payment_method' => null,
                'comment' => 'Отмена по просьбе клиента',
                'user_id' => 2,
                'created_at' => '2026-05-24 10:00:00',
                'updated_at' => '2026-05-28 15:00:00'
            ],
            [
                'type' => 'sale',
                'client_id' => 4,
                'client_name' => null,
                'client_phone' => '+7 (999) 181-18-18',
                'delivery_date' => null,
                'delivery_time' => null,
                'assembly_date' => null,
                'status' => 'completed',
                'total_amount' => 750.00,
                'payment_method' => 'card',
                'comment' => null,
                'user_id' => 2,
                'created_at' => '2026-05-25 13:00:00',
                'updated_at' => '2026-05-25 13:00:00'
            ]
        ]);
    }
}
